### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by hpaknia** [lindelius/laravel-mongo#1]
#First of all thanks, then  I wish you mention somewhere in readme  this package uses this library: https://github.com/mongodb/mongo-php-library
By the way any examples? How I can use count method, How I can set read preference to my primary mongo instance, How ....

**Comment by lindelius** [comment]
Hi @hpmhpm 

Thank you for using this library. If you downloaded it before yesterday, please change the package name in your `composer.json` file as I recently changed it from `lindelius/laravelmongo` to `lindelius/laravel-mongo` (note the added hyphen).

I have now updated the readme file to make it clear that this library is built on top of the official MongoDB PHP library. Thanks for pointing this out!

If you need to configure the database connection, you should be able to specify all the available MongoDB options in the `config/database.php` file, just like in the example config in the readme file. If you need to specify a `readPreference` for your database, you can do so by modifying the config like this:

```php
'mongodb' => [
    'driver'        => 'mongodb',
    'hosts'         => env('DB_HOST', 'localhost:27017'),
    'database'      => env('DB_DATABASE', 'test'),
    'username'      => env('DB_USERNAME', ''),
    'password'      => env('DB_PASSWORD', ''),
    'uriOptions'    => [
        'authSource' => env('DB_AUTHSOURCE', 'admin'),
        'replicaSet' => empty(env('DB_RSNAME')) ? null : env('DB_RSNAME', 'rs1'),
    ],
    'driverOptions' => [
        'readPreference' => new \MongoDB\Driver\ReadPreference(1) // <-- Add this
    ],
],
```

However, do note that the default `readPreference` for MongoDB installations is already set to **primary**. So, if you want to read from your primary you do not need to explicitly specify this. Please see the [MongoDB PHP driver documentation](http://php.net/manual/en/class.mongodb-driver-readpreference.php) for more information regarding the use of `ReadPreference`.

As this library is still in its very early stages, it does not come with any `find` functionality (including `count`). This is something that should probably be included in some sort of facade class.

If you need to make a `count()` operation you can get the `MongoDB\Database` object from the Laravel/Lumen container with the `app('db')` helper function, and then use that to count a collection.

```php
// Somewhere in your code

$collection = app('db')->selectCollection('my_collection');
$count = $collection->count();
```

If you find anything else that's missing, a bug in the code, or if you have any requests, feel free to create issues in this repository and I will respond to them as soon as possible.

**Comment by hpmhpm** [comment]
Cool, thanks for your descriptive answer. I have some suggestions: I created my own wrapper a couple of days ago. I prefered to add my mongo instance as a singleton class; so there is no need to instantiate mongo class if there is no access to the object. By the way I need 2 mongo instances (one is a temp)
```
$app->singleton('m', function() {
    return new App\Helpers\Mongo('main');
});
$app->singleton('mt', function() {
    return new App\Helpers\Mongo('temp');
});
```
Also I don't know what's the benefit of extending db class, while this mongo class can be an independent class. Any way if you don't want to add this class as a singleton, you can postpone Mongo client initiation to the first use:
```
    public function __get($name) {
        if ($this->client == false) {
            // preparing connString, options and driverOptions
            $this->client = new Client($connString, $options, $driverOptions);
            $this->db = $this->client->{$this->dbName};
        }
        return $this->client->selectCollection($this->dbName, $name);
    }
```

**Comment by lindelius** [comment]
The benefit of extending the `Connection` class is that you're able to configure and use the database connection just like you would with any other database connection in Laravel and Lumen. In other words, you can use the `config/database.php` file to store your configuration and then retrieve the connection object by using the `app('db')` helper function. Laravel and Lumen stores the database object internally inside the `Application` singleton object, so there should be no unnecessary instantiation.

If you require multiple database connections you should be able to accomplish this by duplicating the configuration array and the service provider. So, if you want to create another database connection for a "temp" database, you would duplicate the configuration array, name it "mongodb_temp" and change the necessary options. Then you would change the `register()` method in the new copy of the service provider class to the following:

```php
    public function register()
    {
        $this->app->resolving('db_temp', function ($databaseManager) {
            /**
             * @var DatabaseManager $databaseManager
             */
            $databaseManager->extend('mongodb_temp', function ($config) {
                return new MongoDbConnection($config);
            });
        });
    }
```

Then you should be able to access the `MongoDB\Database` object for the "temp" database with

```php
$database = app('db_temp')->getDatabase();
```

Don't forget to register the new service provider in the `config/app.php` (Laravel) or `bootstrap/app.php` (Lumen) file.

**Comment by hpaknia** [comment]
Thanks, Sounds good!

**Comment by lindelius** [comment]
You're welcome :)

Let me know if you run into any issues!
