### ISSUE TITLE
not authorized on test to execute command

### ISSUE THREAD

**Issue by developernaren** [lindelius/laravel-mongo#2]
I am getting this issue when I try to connect to compose

    'mongodb' => [
            'driver'        => 'mongodb',
            'hosts'         => env('MONGO_DB_HOST', 'localhost:27017'),
            'database'      => env('MONGO_DB_DATABASE', 'test'),
            'username'      => env('MONGO_DB_USERNAME', ''),
            'password'      => env('MONGO_DB_PASSWORD', ''),
            'uriOptions'    => [
                'authSource' => env('DB_AUTHSOURCE', 'admin')
            ],
            'driverOptions' => [],
        ],
This is the settings that I am using.

I get this error `not authorized on test to execute command`. I can confirm that the username, password is working because I can connect through shell using the same username and password.

Any help is apreciated :)

**Comment by lindelius** [comment]
Hi @developernaren 

In which database does the MongoDB-user live? Did you create it in the `test` database, the `admin` database, or some other database?

**Comment by developernaren** [comment]
@lindelius it is in the admin database, but I am able to connect to the database using just this?

```
MongoDB\Driver\Manager("mongodb://<username>:<password>@<mongo_server>:<port>/<database>");

    $bulk = new MongoDB\Driver\BulkWrite;
    $bulk->insert(['x' => 1]);
    $bulk->insert(['x' => 2]);
    $bulk->insert(['x' => 3]);
    $manager->executeBulkWrite('db.collection', $bulk);

   $query = new MongoDB\Driver\Query($filter);
   $cursor = $manager->executeQuery('db.collection', $query);

   foreach ($cursor as $document) {
       dd($document);
   }
```

This is the example in php.net I found and this seems to be working as expected. I can write and retrieve data like this.

**Comment by lindelius** [comment]
What database do you substitute `<database>` with in your example? The database which name you put there is the one that you authenticate against, so if you put `test` there and that works, then it means that you have to set `DB_AUTHSOURCE=test` in your `.env` file.

**Comment by developernaren** [comment]
yes that did it, thanks for the help. @lindelius

**Comment by lindelius** [comment]
No problem. Glad I could help :)
